app/controllers/room.py
from _datetime import datetime
from uuid import uuid4
from flask import Blueprint, request, jsonify, session, current_app
from core.services import Page
from core.cupcore.filemanager import FileUploader
from app.schemas import Room, User, Attachment
from ..resources.forms import RoomSettingsForm, RoomSecureLinkForm, \
    AuthorizationUserForm
from ..services.user import hashing_password_by_form, generate_token
from ..services.avatar import send_avatar


room_controller = Blueprint('room', __name__)


room_avatars = FileUploader('_storage/room_avatars/',
                            extensions={'jpg', 'jpeg', 'png', 'bmp'})
                            

@room_controller.route('/', methods=['POST'])
def create():
    form = RoomSettingsForm(request.form)
    if not form.validate():
        return jsonify(errors=form.errors)
        
    user_id = request.cookies.get('uid')
    if not user_id:
        return jsonify(error=1)
    
    room = Room(name=form.name.data,
                user_ids=[user_id],
                lifetime=form.lifetime.data,
                message_lifetime=form.message_lifetime.data)
    room.save()
    
    return jsonify(success=1, rid=str(room.id))


@room_controller.route('/', methods=['PUT'])
def update():
    form = request.form;
    form_data = {key: form.get(key) for key in form.keys() if key != 'rid'}
    
    room = Room.objects(id=form.get('rid')).first()
    if not room:
        return jsonify(error=1)
    
    for key, value in form_data.items():
        setattr(room, key, value)
    
    room.update_at = datetime.utcnow();
    room.save()
    
    return jsonify(success=1)


@room_controller.route('/<room_id>/avatar/')
def icon(room_id):
    current_user_id = request.cookies.get('uid')
    if not current_user_id:
        return Page.not_found()
        
    room = Room.objects(id=room_id, user_ids=current_user_id).first()
    if not room:
        return Page.not_found()
    
    if not room.avatar_id:
        if not room.name and room.is_dialog:
            return Page.not_found()
        
        return send_avatar(room)
    
    avatar = Attachment.objects(id=room.avatar_id).first()
    if not avatar:
        room.avatar_id = None
        room.save()
        
    return room_avatars.send(avatar.filename)
    

@room_controller.route('/<room_id>/avatar/', methods=['POST'])
def upload_icon(room_id):
    current_user_id = request.cookies.get('uid')
    if not current_user_id:
        return jsonify(error=1)
        
    room = Room.objects(id=room_id, user_ids=current_user_id).first()
    if not room:
        return jsonify(error=1)

    files = request.files.getlist('image') \
        + request.form.getlist('image')
    filename = room_avatars.save(files[0], prefix=user_id)
    if not filename:
        return jsonify(error=1)
    
    attachment = Attachment(room_id=room_id, filename=filename)
    attachment.save()
    
    room.avatar_id = str(attachment.id)
    room.save()
        
    return jsonify(success=1)

app/templates/room/activities/create.html
<div id="add_room_activity"
    class="activity"
    ic-activity="add_room"
    ic-url="/rooms/add"
    >
    {%- include 'room/forms/create.html' -%}
</div>

app/templates/room/activities/list.html
{% set activity_name = 'room_list' -%}

<div id="room_list_activity"
    class="activity{% if opened_activity == activity_name %} is-opened{% endif %}"
    ic-activity="{{ activity_name }}"
    ic-url="/rooms/"
    ic-type="list:rooms"
    >
    <div class="activity__header">
        <i class="activity__back material-icons" ic-open-sidebar="menu">&#xE5D2;</i>
        <h2>Комнаты</h2>
    </div>
    <div class="activity__body has-float-button">
        <ul class="list"></ul>
        <p class="activity__body-info">Список комнат пуст</p>
    </div>
    <button class="button button--floating icon icon--add"
        type="button"
        ic-open-activity="add_room">
    </button>
</div>

app/templates/room/activities/messager.html
<div id="messager_activity"
    class="activity messager activity--empty"
    ic-activity="messager"
    ic-url="/"
    ic-type="messager"
    >
    <div class="activity__header activity__header--actions">
        <i class="activity__back material-icons">&#xE5CD;</i>
        <h2>0</h2>
        <div class="activity__actions">
            <i class="material-icons js-action-edit is-hidden">&#xE254;</i>
            <i class="material-icons js-action-save is-hidden">&#xE161;</i>
            <i class="material-icons js-action-delete">&#xE872;</i>
        </div>
    </div>
    <div class="activity__header">
        <i class="activity__back material-icons" ic-close-activity>&#xE5C4;</i>
        <h2 ic-open-activity="room_settings"></h2>
        <div class="room-info room-info--light"></div>
        <div class="activity__avatar avatar"></div>
        <a class="messager__unread-button button button--floating icon icon--unread is-hidden">0</a>
    </div>
    <div class="activity__body">
        <ul class="list messager__list"></ul>
    </div>
    <div class="activity__info">
        <p>Пожалуйста выберите комнату для начала общения</p>
    </div>
    <div class="activity__footer">
        <ul class="messager__preview"></ul>
        <div class="emoji-container is-hidden">
            <div class="emoji-container__body">
                <div class="emoji-container__list"></div>
            </div>
            <div class="emoji-container__tabs">
                {# todo: Популярные смайлы #}
                {#<i class="emoji-container__tab material-icons">&#xE192;</i>#}
                <i class="emoji-container__tab material-icons" data-page="people">&#xE7F2;</i>
                <i class="emoji-container__tab material-icons" data-page="nature">&#xE91D;</i>
                <i class="emoji-container__tab material-icons" data-page="food-drink">&#xE556;</i>
                <i class="emoji-container__tab material-icons" data-page="travel-places">&#xE531;</i>
                <i class="emoji-container__tab material-icons" data-page="symbols">&#xE52E;</i>
                {# todo: Поиск по смайлам #}
                {#<i class="emoji-container__tab material-icons">&#xE8B6;</i>#}
            </div>
        </div>
        <span class="messager__send icon icon--send"></span>
        <i class="messager__edit icon material-icons">&#xE254;</i>
        <label class="messager__attach icon icon--attach" for=image>
            <input id=image type=file multiple name=image accept="image/*">
        </label>
        <div class="messager__textarea">
            <textarea placeholder="Введите текст"></textarea>
        </div>
        <i class="messager__emoji icon material-icons">&#xE24E;</i>
    </div>
</div>

app/templates/room/activities/settings.html
<div id="room_settings_activity"
    class="activity"
    ic-activity="room_settings"
    ic-url="/rooms/settings"
    ic-type="settings"
    >
    <div class="activity__header">
        <i class="activity__back material-icons" ic-close-activity>&#xE5C4;</i>
        <h2>Настройки комнаты</h2>
    </div>
    <div class="activity__body has-float-button">
        <ul class="list list--preferences"
            ic-action="{{ url_for('room.update') }}"
            >
            <li class="list__item preference"
                ic-key="name"
                ic-type="text">
                <h2 class="preference__title">Название комнаты</h2>
                <p class="preference__summary"></p>
            </li>
            <li class="list__item preference"
                ic-key="lifetime"
                ic-type="range"
                ic-range-min="0"
                ic-range-max="360"
                ic-range-step="10"
                ic-icon="trash"
                >
                <h2 class="preference__title">Время жизни комнаты</h2>
                <p class="preference__summary" ic-format>%d минут</p>
            </li>
            <li class="list__item preference"
                ic-key="message_lifetime"
                ic-type="range"
                ic-range-min="0"
                ic-range-max="360"
                ic-range-step="10"
                ic-icon="trash"
                >
                <h2 class="preference__title">Время жизни сообщений</h2>
                <p class="preference__summary" ic-format>%d секунд</p>
            </li>
        </ul>
    </div>
</div>